import { PartyPlan } from "../types";

export interface DriveExportResult {
  success: boolean;
  fileId?: string;
  webViewLink?: string;
  error?: string;
}

/**
 * Formats a Party Plan into a clean, professional Markdown party dossier.
 */
export function formatPlanToMarkdown(plan: PartyPlan): string {
  const dateStr = new Date(plan.createdAt).toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  let md = `# 🎉 ${plan.title.toUpperCase()} - PARTY DOSSIER\n`;
  md += `**Occasion:** ${plan.occasion} | **Theme:** ${plan.theme}\n`;
  md += `**Created:** ${dateStr}\n`;
  md += `**Guest Count:** ${plan.guestConfig.adultCount} Adults, ${plan.guestConfig.childCount} Kids\n`;
  md += `**Target Budget:** $${plan.budgetTotal} | **Estimated Cost:** $${plan.budgetSummary?.totalEstimatedCost || plan.budgetTotal}\n`;
  md += `**Tagline:** _${plan.tagline}_\n\n`;

  md += `## 🌟 VIBE & ATMOSPHERE\n`;
  md += `${plan.vibeDescription}\n\n`;
  if (plan.colorPalette?.length) {
    md += `**Color Palette:** ${plan.colorPalette.map(c => `${c.name} (${c.hex})`).join(", ")}\n\n`;
  }

  md += `## 🧮 PORTION & DRINK METRICS\n`;
  md += `- **Total Drink Servings:** ~${plan.portionGuide.totalEstimatedDrinks}\n`;
  md += `- **Cocktails / Mixed Drinks:** ~${plan.portionGuide.cocktailsCount}\n`;
  md += `- **Beer & Wine Bottles:** ~${plan.portionGuide.beerWineBottles}\n`;
  md += `- **Non-Alcoholic Drinks:** ~${plan.portionGuide.nonAlcoholicServings}\n`;
  md += `- **Party Ice Needed:** ${plan.portionGuide.iceBagsRequiredLbs} lbs\n`;
  md += `- **Main Proteins / Meats:** ${plan.portionGuide.mainProteinLbs} lbs\n`;
  md += `- **Appetizers & Finger Food:** ~${plan.portionGuide.appetizerPiecesTotal} pieces\n\n`;

  md += `## 🛒 MASTER SHOPPING LIST (BY STORE)\n`;
  // Group by store
  const storeGroups: Record<string, typeof plan.shoppingItems> = {};
  plan.shoppingItems.forEach(item => {
    const store = item.storeType || "General Store";
    if (!storeGroups[store]) storeGroups[store] = [];
    storeGroups[store].push(item);
  });

  for (const [store, items] of Object.entries(storeGroups)) {
    md += `### 🏪 ${store}\n`;
    items.forEach(item => {
      const check = item.isChecked ? "[x]" : "[ ]";
      const dietary = item.dietaryTag ? ` _(${item.dietaryTag})_` : "";
      const notes = item.notes ? ` — *Note: ${item.notes}*` : "";
      md += `- ${check} **${item.name}** | Qty: ${item.quantity} | Est: $${item.estimatedCost.toFixed(2)}${dietary}${notes}\n`;
    });
    md += `\n`;
  }

  md += `## 🍽️ CURATED MENU & RECIPES\n`;
  plan.menu.forEach(m => {
    md += `### ${m.name} (${m.type})\n`;
    md += `- **Prep Time:** ${m.prepTimeMinutes} mins | **Servings:** ${m.servings}\n`;
    md += `- **Dietary:** ${m.dietaryInfo.join(", ") || "Standard"}\n`;
    md += `- **Description:** ${m.description}\n`;
    if (m.keyIngredients?.length) {
      md += `- **Key Ingredients:** ${m.keyIngredients.join(", ")}\n`;
    }
    if (m.recipeHighlights?.length) {
      md += `- **Prep Steps:**\n`;
      m.recipeHighlights.forEach((step, idx) => {
        md += `  ${idx + 1}. ${step}\n`;
      });
    }
    md += `\n`;
  });

  md += `## ⏰ COUNTDOWN & PREPARATION TIMELINE\n`;
  plan.prepTimeline.forEach(t => {
    const check = t.isDone ? "[x]" : "[ ]";
    md += `- ${check} **[${t.phase}]** ${t.task} ${t.details ? `_(${t.details})_` : ""}\n`;
  });
  md += `\n`;

  md += `## 💡 MONEY-SAVING ADVICE\n`;
  (plan.budgetSummary?.moneySavingTips || []).forEach(tip => {
    md += `- 💡 ${tip}\n`;
  });
  md += `\n`;

  md += `## 🎵 PLAYLIST & AMBIENCE\n`;
  md += `- **Genre / Vibe:** ${plan.playlistVibe?.genre || "Party Hits"}\n`;
  md += `- **Suggested Tracks:** ${(plan.playlistVibe?.sampleTracks || []).join(", ")}\n`;
  md += `- **Lighting Tip:** ${plan.playlistVibe?.lightingTip || ""}\n`;
  md += `- **Icebreaker:** ${plan.playlistVibe?.icebreakerIdea || ""}\n\n`;

  md += `---\n*Generated by Party Planner Shopping Agent*\n`;

  return md;
}

/**
 * Formats shopping items into CSV format for Google Sheets / Excel import.
 */
export function formatPlanToCSV(plan: PartyPlan): string {
  const headers = ["Category", "Item Name", "Quantity", "Store Recommended", "Estimated Cost ($)", "Status", "Priority", "Dietary Tag", "Notes"];
  const rows = plan.shoppingItems.map(item => [
    `"${item.category.replace(/"/g, '""')}"`,
    `"${item.name.replace(/"/g, '""')}"`,
    `"${item.quantity.replace(/"/g, '""')}"`,
    `"${item.storeType.replace(/"/g, '""')}"`,
    item.estimatedCost.toFixed(2),
    item.isChecked ? "Purchased" : item.status === "already_have" ? "Already Have" : "To Buy",
    item.priority,
    `"${(item.dietaryTag || "").replace(/"/g, '""')}"`,
    `"${(item.notes || "").replace(/"/g, '""')}"`,
  ]);

  return [headers.join(","), ...rows.map(r => r.join(","))].join("\n");
}

/**
 * Uploads a file directly to Google Drive using the Drive v3 REST API.
 */
export async function uploadToGoogleDrive(
  accessToken: string,
  fileName: string,
  content: string,
  mimeType: string = "text/plain"
): Promise<DriveExportResult> {
  try {
    const metadata = {
      name: fileName,
      mimeType: mimeType,
      description: "Created by Party Planner Shopping Agent",
    };

    const boundary = "-------314159265358979323846";
    const delimiter = `\r\n--${boundary}\r\n`;
    const closeDelimiter = `\r\n--${boundary}--`;

    const multipartRequestBody =
      delimiter +
      "Content-Type: application/json; charset=UTF-8\r\n\r\n" +
      JSON.stringify(metadata) +
      delimiter +
      `Content-Type: ${mimeType}\r\n\r\n` +
      content +
      closeDelimiter;

    const response = await fetch(
      "https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,webViewLink",
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          "Content-Type": `multipart/related; boundary=${boundary}`,
        },
        body: multipartRequestBody,
      }
    );

    if (!response.ok) {
      const errText = await response.text();
      return {
        success: false,
        error: `Drive API returned ${response.status}: ${errText}`,
      };
    }

    const data = await response.json();
    return {
      success: true,
      fileId: data.id,
      webViewLink: data.webViewLink || `https://drive.google.com/file/d/${data.id}/view`,
    };
  } catch (err: any) {
    return {
      success: false,
      error: err.message || "Failed to upload to Google Drive",
    };
  }
}
